apiVersion: v1
kind: Service
metadata:
  name: mytomcat-app-service
spec:
  type: NodePort
  selector:
    app: mytomcat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

